language: python

# Python 3.5 specified to make tox environment 'py35' work.
# See: https://github.com/travis-ci/travis-ci/issues/4794
python:
  - 3.5

notifications:
    false

# Environment changes have to be manually synced with 'tox.ini'.
# See: https://github.com/travis-ci/travis-ci/issues/3024
env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

install:
  - pip install -U setuptools
  - pip install tox

script:
  tox
